query page($slug: String!) {
	page: Page(slug: $slug) {
	  isPublished
	  title
	  text
	  header {
	  	image {
	  		handle
	  	}
	  	text
	  	callToAction {
	  		text
	  		url
	  		internalLink
	  	}
	  }
	  media {
	  	id
	    handle
	  }
	  callToActions {
	  	text
	  	url
	  	internalLink
	  }
	  features {
	    title
	    description
	    icon {
	    	handle
	    }
	  }
	}
}
