query page($slug: String!) {
	page: Page(slug: $slug) {
	  isPublished
	  title
	  headerImage {
	  	id
	    sort
	    handle
	  }
	  features(filter: {isPublished: true}) {
	    title
	    description
	  }
	}
}
