query project($slug: String!) {
	project: Project(slug: $slug) {
	  isPublished
	  title
	  releaseDate
	  projectURL
	  types
	  client
	  media {
	  	id
	    sort
	    handle
	  }
	  features(filter: {isPublished: true}) {
	    title
	    description
	  }
	  callToActions {
	  	text
	  	url
	  	internalLink
	  }
	}
}
